---
title: "Regression"
---

```{r Global, echo=FALSE, message=FALSE, warning=FALSE}
source("Global.R")
```

# {.tabset .tabset-pills}
## PD-L1 {.tabset .tabset-pills}
### Unadjusted model
```{r pdl1_unadjusted}
library(questionr)
pdl1_tumor_unadjusted <- glm(high_grade ~ pdl1_tumor, family = "binomial", data = DB)
kable(
  odds.ratio(pdl1_tumor_unadjusted),
  align = c("c"),
  caption = "PD-L1 expression in tumor cells"
)

pdl1_lymph_unadjusted <- glm(high_grade ~ pdl1_lymph, family = "binomial", data = DB)
kable(
  odds.ratio(pdl1_lymph_unadjusted),
  align = c("c"),
  caption = "PD-L1 expression in peritumoral lymphocytes"
)

```

### Adjusted model
```{r pdl1_adjusted}
library(questionr)
pdl1_log_adjusted <- glm(
  high_grade ~ pdl1_tumor + pdl1_lymph,
  family = "binomial",
  data = DB
)
kable(
  odds.ratio(pdl1_log_adjusted),
  align = c("c"),
  caption = "PD-L1 expression in tumor cells and peritumoral lymphocytes"
)

```

## FOXP3 {.tabset .tabset-pills}
### Unadjusted model
```{r foxp3_unadjusted}
foxp3_lymph_tumor_unadjusted <- glm(
  high_grade ~ foxp3_lymph_tumor, family = "binomial", data = DB
)
kable(
  odds.ratio(foxp3_lymph_tumor_unadjusted),
  align = c("c"),
  caption = "FOXP3 expression in intratumoral lymphocytes"
)

foxp3_lymph_stroma_unadjusted <- glm(
  high_grade ~ foxp3_lymph_stroma, family = "binomial", data = DB
)
kable(
  odds.ratio(foxp3_lymph_stroma_unadjusted),
  align = c("c"),
  caption = "FOXP3 expression in peritumoral lymphocytes"
)
```

### Adjusted model
```{r foxp3_adjusted}
foxp3_log_adjusted <- glm(
  high_grade ~ foxp3_lymph_tumor + foxp3_lymph_stroma,
  family = "binomial",
  data = DB
)
kable(
  odds.ratio(foxp3_log_adjusted),
  align = c("c"),
  caption = "FOXP3 expression in intratumoral and peritumoral lymphocytes"
)
```

## CD8+ {.tabset .tabset-pills}
### Unadjusted model
```{r cd8_unadjusted}
cd8_tumor_unadjusted <- glm(
  high_grade ~ cd8_tumor, family = "binomial", data = DB
)
kable(
  odds.ratio(cd8_tumor_unadjusted),
  align = c("c"),
  caption = "CD8+ expression in intratumoral lymphocytes"
)

cd8_stroma_unadjusted <- glm(
  high_grade ~ cd8_stroma, family = "binomial", data = DB
)
kable(
  odds.ratio(cd8_stroma_unadjusted),
  align = c("c"),
  caption = "CD8+ expression in peritumoral lymphocytes"
)
```

### Adjusted model
```{r cd8_adjusted}
cd8_log_adjusted <- glm(
  high_grade ~ cd8_tumor + cd8_stroma,
  family = "binomial",
  data = DB
)
kable(
  odds.ratio(cd8_log_adjusted),
  align = c("c"),
  caption = "CD8+ expression in intratumoral and peritumoral lymphocytes"
)
```

## Double CD8+/Ki67+ {.tabset .tabset-pills}
### Unadjusted model
```{r cd8ki67_unadjusted}
cd8ki67_tumor_unadjusted <- glm(
  high_grade ~ cd8ki67_tumor, family = "binomial", data = DB
)
kable(
  odds.ratio(cd8ki67_tumor_unadjusted),
  align = c("c"),
  caption = "Double CD8+/Ki67+ expression in intratumoral lymphocytes"
)

cd8ki67_stroma_unadjusted <- glm(
  high_grade ~ cd8ki67_stroma, family = "binomial", data = DB
)
kable(
  odds.ratio(cd8ki67_stroma_unadjusted),
  align = c("c"),
  caption = "Double CD8+/Ki67+ expression in peritumoral lymphocytes"
)
```

### Adjusted model
```{r cd8ki67_adjusted}
cd8ki67_log_adjusted <- glm(
  high_grade ~ cd8ki67_tumor + cd8ki67_stroma,
  family = "binomial",
  data = DB
)
kable(
  odds.ratio(cd8ki67_log_adjusted),
  align = c("c"),
  caption = "Double CD8+/Ki67+ expression in intratumoral and peritumoral lymphocytes"
)
```
